name: Java CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: /vat-project/.github/workflows/mvnw clean install
        working-directory: vat-project
      - name: Archive production artifacts
        if: always()
        uses: actions/upload-artifact@v2        
        with:
          name: dist-without-markdown
          path: |
            target/surefire-report
